name: CI

on:
  push:
    branches: ["main"]
    tags:
      - "v*"
  pull_request:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up cargo-ndk
        run: cargo install cargo-ndk

      - name: set up aarch64 target
        run: rustup target add aarch64-linux-android

      - name: build
        run: cargo ndk --target aarch64-linux-android build --release

      - name: move files
        run: |
          mv target/aarch64-linux-android/release/linjector-cli ./linjector-cli

      - name: save hashes in env
        run: |
          echo '```' > hashes.txt
          echo "SHA256 hashes:" >> hashes.txt
          sha256sum linjector-cli >> hashes.txt
          echo '```' >> hashes.txt

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          body_path: hashes.txt
          files: |
            ./linjector-cli
